packages:
  # the root package.json
  # - '.'
  # all apps are inside apps directories
  - "apps/**"
  # all packages in subdirs of packages/ and components/
  - "packages/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
